### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by HydrelioxGitHub** [david1983/eBtn#1]
Hello,

Thanks for your library. I'm trying to use it on a ESP8266-12 project I'm working on.
I've tried your example sketch but nothing happen except "This is inside the for loop".

Does it need to have a resistor between the button and the ground or not ?

I've also use this setup : https://github.com/esp8266/Arduino/issues/584#issuecomment-123715951
So the pin can be match in Arduino IDE.

DO you think there could be a problem using your library on a ESP8266 ?

**Comment by david1983** [comment]
Hi, thank you for the comment, the example uses interrupts to call the button handle() method, I don't know if the ESP8266 supports interrupts though.
You can try to uncomment line 62 to see if that works, in that way the button will be handled inside the main loop of the application.
